export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS'; // SERVE PARA CRIAR AS AÇOES AQUI, PARA FICAR ORGANIZADO
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST'; // SERVE PARA CRIAR AS AÇOES AQUI, PARA FICAR ORGANIZADO
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE'; // SERVE PARA CRIAR AS AÇOES AQUI, PARA FICAR ORGANIZADO
